### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by arpad-m** [ashleymaxine/loweralpha#2]
In der Mail habe ich gelesen, dass ihr das Projekt für jeden offen zur Verfügung stellen wollt. Eine open source-Lizenz ist hierfür der richtige Weg: http://choosealicense.com/

Am populärsten ist die MIT-Lizenz. Der Link enthält infos, wie man das Programm unter die Lizenz stellt: http://choosealicense.com/licenses/mit/

**Comment by muellerju** [comment]
Vielen Dank für die hilfreichen Weblinks. Das Projekt steht nun als unter GLPv3 zur Verfügung.
